/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 健康检查 */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/content/pages/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取页面内容（home / world） */
        get: operations["getContentPage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/content/pages/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 保存页面内容（管理员写） */
        put: operations["putContentPage"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 注册用户 */
        post: operations["registerUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取当前用户资料 */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 更新当前用户资料 */
        patch: operations["updateCurrentUser"];
        trace?: never;
    };
    "/users/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取公开用户资料 */
        get: operations["getUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 登录或刷新令牌 */
        post: operations["createSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sessions/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 登出并撤销会话 */
        delete: operations["deleteSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wiki/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取 Wiki 分类 */
        get: operations["listWikiCategories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wiki/pages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取 Wiki 页面列表 */
        get: operations["listWikiPages"];
        put?: never;
        /** 创建 Wiki 页面 */
        post: operations["createWikiPage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wiki/pages/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取 Wiki 页面 */
        get: operations["getWikiPage"];
        put?: never;
        post?: never;
        /** 删除 Wiki 页面 */
        delete: operations["deleteWikiPage"];
        options?: never;
        head?: never;
        /** 更新 Wiki 页面 */
        patch: operations["updateWikiPage"];
        trace?: never;
    };
    "/wiki/pages/{slug}/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取版本历史 */
        get: operations["listWikiPageRevisions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wiki/pages/{slug}/revisions/{revisionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取指定版本 */
        get: operations["getWikiPageRevision"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/guides": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取攻略列表 */
        get: operations["listGuides"];
        put?: never;
        /** 创建攻略 */
        post: operations["createGuide"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/guides/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取攻略详情 */
        get: operations["getGuide"];
        put?: never;
        post?: never;
        /** 删除攻略 */
        delete: operations["deleteGuide"];
        options?: never;
        head?: never;
        /** 更新攻略 */
        patch: operations["updateGuide"];
        trace?: never;
    };
    "/guides/{slug}/ratings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取攻略评分汇总 */
        get: operations["getGuideRating"];
        put?: never;
        /** 提交或更新评分 */
        post: operations["rateGuide"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/forum/boards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取论坛板块 */
        get: operations["listForumBoards"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/forum/boards/{boardSlug}/threads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取板块内主题列表 */
        get: operations["listForumThreads"];
        put?: never;
        /** 发布主题 */
        post: operations["createForumThread"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/forum/threads/{threadId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取主题详情 */
        get: operations["getForumThread"];
        put?: never;
        post?: never;
        /** 删除主题 */
        delete: operations["deleteForumThread"];
        options?: never;
        head?: never;
        /** 更新主题 */
        patch: operations["updateForumThread"];
        trace?: never;
    };
    "/forum/threads/{threadId}/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取主题回复列表 */
        get: operations["listForumPosts"];
        put?: never;
        /** 发表回复 */
        post: operations["createForumPost"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/forum/posts/{postId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 删除回复 */
        delete: operations["deleteForumPost"];
        options?: never;
        head?: never;
        /** 编辑回复 */
        patch: operations["updateForumPost"];
        trace?: never;
    };
    "/forum/posts/{postId}/like": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 点赞回复 */
        put: operations["likeForumPost"];
        post?: never;
        /** 取消点赞 */
        delete: operations["unlikeForumPost"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/forum/threads/{threadId}/bookmark": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 收藏主题 */
        put: operations["bookmarkThread"];
        post?: never;
        /** 取消收藏 */
        delete: operations["unbookmarkThread"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wiki/pages/{slug}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取 Wiki 页面评论 */
        get: operations["listWikiComments"];
        put?: never;
        /** 发表 Wiki 评论 */
        post: operations["createWikiComment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/guides/{slug}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取攻略评论 */
        get: operations["listGuideComments"];
        put?: never;
        /** 发表攻略评论 */
        post: operations["createGuideComment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/comments/{commentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 删除评论 */
        delete: operations["deleteComment"];
        options?: never;
        head?: never;
        /** 编辑评论 */
        patch: operations["updateComment"];
        trace?: never;
    };
    "/comments/{commentId}/like": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 点赞评论 */
        put: operations["likeComment"];
        post?: never;
        /** 取消点赞 */
        delete: operations["unlikeComment"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 跨内容搜索 */
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 上传文件 */
        post: operations["uploadFile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads/presign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 获取预签名上传地址 */
        post: operations["presignUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /**
             * Format: uri
             * @example https://api.nodusfall.example.com/errors/validation-error
             */
            type: string;
            /** @example Validation Error */
            title: string;
            /** @example 400 */
            status: number;
            /** @example 请求参数校验失败 */
            detail?: string;
            /** Format: uri */
            instance?: string;
            /** @example VALIDATION_ERROR */
            code?: string;
            /** @example req_01J0ABCDEF */
            requestId?: string;
            errors?: components["schemas"]["ValidationIssue"][];
        };
        ValidationIssue: {
            /** @example email */
            field: string;
            /** @example INVALID_FORMAT */
            code: string;
            /** @example email 必须是有效的邮箱地址 */
            message: string;
        };
        Pagination: {
            /** @example 1 */
            page: number;
            /** @example 20 */
            perPage: number;
            /** @example 128 */
            total: number;
            /** @example 7 */
            totalPages: number;
            /** @example true */
            hasMore: boolean;
        };
        Health: {
            /** @enum {string} */
            status: "ok" | "degraded";
            /** @example 1.0.0 */
            version: string;
            dependencies?: {
                [key: string]: string;
            };
        };
        UserSummary: {
            /** Format: uuid */
            id: string;
            username: string;
            displayName: string;
            /** Format: uri */
            avatarUrl?: string;
            /** @enum {string} */
            role: "guest" | "member" | "editor" | "moderator" | "admin";
            /** Format: date-time */
            createdAt: string;
        };
        User: components["schemas"]["UserSummary"] & {
            bio?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        AuthSession: {
            accessToken: string;
            refreshToken: string;
            /** @example Bearer */
            tokenType: string;
            /** @example 900 */
            expiresIn: number;
            /** Format: uuid */
            sessionId: string;
            user: components["schemas"]["User"];
        };
        WikiCategory: {
            /** Format: uuid */
            id: string;
            slug: string;
            name: string;
            description?: string;
            sortOrder: number;
        };
        WikiCategoryList: {
            data: components["schemas"]["WikiCategory"][];
        };
        WikiPageSummary: {
            /** Format: uuid */
            id: string;
            slug: string;
            title: string;
            excerpt: string;
            categorySlug: string;
            tags: string[];
            /** @enum {string} */
            status: "draft" | "published" | "archived";
            author: components["schemas"]["UserSummary"];
            /** Format: date-time */
            updatedAt: string;
        };
        WikiPage: components["schemas"]["WikiPageSummary"] & {
            content: string;
            version: number;
            /** Format: date-time */
            createdAt: string;
            revisionCount: number;
        };
        WikiPageList: {
            data: components["schemas"]["WikiPageSummary"][];
            pagination: components["schemas"]["Pagination"];
        };
        WikiPageRevision: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            pageId: string;
            version: number;
            title: string;
            content: string;
            changelog: string;
            author: components["schemas"]["UserSummary"];
            /** Format: date-time */
            createdAt: string;
        };
        WikiPageRevisionList: {
            data: components["schemas"]["WikiPageRevision"][];
            pagination: components["schemas"]["Pagination"];
        };
        GuideSummary: {
            /** Format: uuid */
            id: string;
            slug: string;
            title: string;
            excerpt: string;
            tags: string[];
            /** @enum {string} */
            status: "draft" | "published" | "archived";
            author: components["schemas"]["UserSummary"];
            rating: number;
            ratingCount?: number;
            /** Format: date-time */
            updatedAt: string;
        };
        Guide: components["schemas"]["GuideSummary"] & {
            content: string;
            relatedCharacter?: string;
            /** Format: date-time */
            createdAt: string;
        };
        GuideList: {
            data: components["schemas"]["GuideSummary"][];
            pagination: components["schemas"]["Pagination"];
        };
        RatingSummary: {
            /** @example 4.6 */
            average: number;
            /** @example 42 */
            count: number;
            /** @example 4 */
            myScore: number | null;
            /**
             * @example {
             *       "1": 1,
             *       "2": 0,
             *       "3": 3,
             *       "4": 12,
             *       "5": 26
             *     }
             */
            distribution: {
                [key: string]: number;
            };
        };
        ForumBoard: {
            /** Format: uuid */
            id: string;
            slug: string;
            name: string;
            description?: string;
            sortOrder: number;
            threadCount: number;
        };
        ForumBoardList: {
            data: components["schemas"]["ForumBoard"][];
        };
        ForumThreadSummary: {
            /** Format: uuid */
            id: string;
            boardSlug: string;
            title: string;
            excerpt: string;
            /** Format: uri */
            coverImage: string | null;
            author: components["schemas"]["UserSummary"];
            pinned: boolean;
            locked: boolean;
            replyCount: number;
            likeCount: number;
            bookmarkedByMe: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            lastPostAt: string;
        };
        ForumThread: components["schemas"]["ForumThreadSummary"] & {
            content: string;
        };
        ForumThreadList: {
            data: components["schemas"]["ForumThreadSummary"][];
            pagination: components["schemas"]["Pagination"];
        };
        ForumPost: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            threadId: string;
            author: components["schemas"]["UserSummary"];
            content: string;
            floor: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            likeCount: number;
            likedByMe: boolean;
        };
        ForumPostList: {
            data: components["schemas"]["ForumPost"][];
            pagination: components["schemas"]["Pagination"];
        };
        Comment: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            targetType: "wiki_page" | "guide";
            targetId: string;
            author: components["schemas"]["UserSummary"];
            content: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            likeCount: number;
            likedByMe: boolean;
        };
        CommentList: {
            data: components["schemas"]["Comment"][];
            pagination: components["schemas"]["Pagination"];
        };
        SearchResult: {
            /** @enum {string} */
            kind: "wiki" | "guide" | "forum";
            id: string;
            title: string;
            excerpt: string;
            url: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        SearchResponse: {
            data: components["schemas"]["SearchResult"][];
            pagination: components["schemas"]["Pagination"];
        };
        Upload: {
            /** Format: uuid */
            id: string;
            /** Format: uri */
            url: string;
            key: string;
            mimeType: string;
            size: number;
            /** Format: date-time */
            createdAt: string;
        };
        PresignedUpload: {
            /** Format: uri */
            uploadUrl: string;
            key: string;
            /** Format: uri */
            url: string;
            expiresIn: number;
        };
        ContentMeta: {
            pageId: string;
            updatedAt: string;
            maintainer: string;
            note: string;
        };
        MediaSlot: {
            /** @enum {string} */
            kind: "image" | "video";
            src: string;
            alt: string;
            poster: string;
        };
        Cta: {
            label: string;
            href: string;
            /** @enum {string} */
            style: "primary" | "ghost";
        };
        HomeHero: {
            hidden?: boolean;
            kicker: string;
            title: string;
            lead: string;
            media: components["schemas"]["MediaSlot"];
            ctas: components["schemas"]["Cta"][];
        };
        HomeNotice: {
            hidden?: boolean;
            text: string;
            linkLabel: string;
            linkHref: string;
        };
        HomeEntryCard: {
            title: string;
            desc: string;
            href: string;
            media: components["schemas"]["MediaSlot"];
        };
        HomeEntries: {
            hidden?: boolean;
            title: string;
            cards: components["schemas"]["HomeEntryCard"][];
        };
        HomeDigestItem: {
            date: string;
            tag: string;
            title: string;
            url: string;
            excerpt: string;
            image: string;
        };
        HomeDigestColumn: {
            title: string;
            emptyText: string;
            items: components["schemas"]["HomeDigestItem"][];
        };
        HomeDigest: {
            hidden?: boolean;
            latest: components["schemas"]["HomeDigestColumn"];
            featured: components["schemas"]["HomeDigestColumn"];
        };
        HomePageContent: {
            meta: components["schemas"]["ContentMeta"];
            sections: ("hero" | "notice" | "digest" | "entries")[];
            hero: components["schemas"]["HomeHero"];
            notice: components["schemas"]["HomeNotice"];
            digest: components["schemas"]["HomeDigest"];
            entries: components["schemas"]["HomeEntries"];
        };
        WorldHero: {
            hidden?: boolean;
            kicker: string;
            title: string;
            subtitle: string;
            lead: string;
            art: components["schemas"]["MediaSlot"];
            chips: {
                label: string;
                value: string;
            }[];
            ctas: components["schemas"]["Cta"][];
        };
        WorldOverview: {
            hidden?: boolean;
            title: string;
            lead: string;
            facts: {
                label: string;
                value: string;
            }[];
        };
        WorldviewEntry: {
            no: string;
            title: string;
            en: string;
            body: string;
            tag: string;
            image: components["schemas"]["MediaSlot"];
        };
        WorldWorldview: {
            hidden?: boolean;
            title: string;
            intro: string;
            entries: components["schemas"]["WorldviewEntry"][];
        };
        GameplayFeature: {
            no: string;
            title: string;
            body: string;
            image: components["schemas"]["MediaSlot"];
        };
        WorldGameplay: {
            hidden?: boolean;
            title: string;
            intro: string;
            features: components["schemas"]["GameplayFeature"][];
        };
        WorldOfficialLink: {
            label: string;
            url: string;
            desc: string;
        };
        WorldOfficial: {
            hidden?: boolean;
            title: string;
            links: components["schemas"]["WorldOfficialLink"][];
        };
        RepostItem: {
            date: string;
            source: string;
            title: string;
            url: string;
            excerpt: string;
            media: components["schemas"]["MediaSlot"];
        };
        WorldReposts: {
            hidden?: boolean;
            title: string;
            intro: string;
            emptyText: string;
            items: components["schemas"]["RepostItem"][];
        };
        NewsItem: {
            date: string;
            tag: string;
            title: string;
            url: string;
            excerpt: string;
            media: components["schemas"]["MediaSlot"];
        };
        WorldNews: {
            hidden?: boolean;
            title: string;
            emptyText: string;
            items: components["schemas"]["NewsItem"][];
        };
        WorldPageContent: {
            meta: components["schemas"]["ContentMeta"];
            sections: ("hero" | "overview" | "worldview" | "gameplay" | "official" | "reposts" | "news")[];
            hero: components["schemas"]["WorldHero"];
            overview: components["schemas"]["WorldOverview"];
            worldview: components["schemas"]["WorldWorldview"];
            gameplay: components["schemas"]["WorldGameplay"];
            official: components["schemas"]["WorldOfficial"];
            reposts: components["schemas"]["WorldReposts"];
            news: components["schemas"]["WorldNews"];
        };
        ContentPageResponse: {
            data: components["schemas"]["HomePageContent"] | components["schemas"]["WorldPageContent"];
        };
        ContentPageWrite: components["schemas"]["HomePageContent"] | components["schemas"]["WorldPageContent"];
    };
    responses: {
        /** @description 请求校验失败 */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://api.nodusfall.example.com/errors/validation-error",
                 *       "title": "Validation Error",
                 *       "status": 400,
                 *       "detail": "请求参数校验失败",
                 *       "code": "VALIDATION_ERROR",
                 *       "requestId": "req_01J0ABCDEF",
                 *       "errors": [
                 *         {
                 *           "field": "email",
                 *           "code": "INVALID_FORMAT",
                 *           "message": "email 必须是有效的邮箱地址"
                 *         }
                 *       ]
                 *     }
                 */
                "application/problem+json": components["schemas"]["Error"];
            };
        };
        /** @description 未认证或令牌无效 */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://api.nodusfall.example.com/errors/unauthorized",
                 *       "title": "Unauthorized",
                 *       "status": 401,
                 *       "code": "UNAUTHENTICATED"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Error"];
            };
        };
        /** @description 权限不足 */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://api.nodusfall.example.com/errors/forbidden",
                 *       "title": "Forbidden",
                 *       "status": 403,
                 *       "code": "FORBIDDEN"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Error"];
            };
        };
        /** @description 资源不存在 */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://api.nodusfall.example.com/errors/not-found",
                 *       "title": "Not Found",
                 *       "status": 404,
                 *       "code": "NOT_FOUND"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Error"];
            };
        };
        /** @description 资源冲突 */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://api.nodusfall.example.com/errors/conflict",
                 *       "title": "Conflict",
                 *       "status": 409,
                 *       "code": "CONFLICT"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Error"];
            };
        };
        /** @description 触发限流 */
        RateLimited: {
            headers: {
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://api.nodusfall.example.com/errors/rate-limited",
                 *       "title": "Too Many Requests",
                 *       "status": 429,
                 *       "code": "RATE_LIMITED"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        Slug: string;
        Page: number;
        PerPage: number;
    };
    requestBodies: {
        RegisterRequest: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    username: string;
                    password: string;
                };
            };
        };
        AuthSessionRequest: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    grantType: "password" | "refreshToken";
                    /** Format: email */
                    email?: string;
                    password?: string;
                    refreshToken?: string;
                };
            };
        };
        UpdateCurrentUserRequest: {
            content: {
                "application/json": {
                    displayName?: string;
                    /** Format: uri */
                    avatarUrl?: string;
                    bio?: string;
                };
            };
        };
        CreateWikiPageRequest: {
            content: {
                "application/json": {
                    title: string;
                    slug?: string;
                    categorySlug: string;
                    tags?: string[];
                    content: string;
                    /**
                     * @default draft
                     * @enum {string}
                     */
                    status?: "draft" | "published";
                    changelog?: string;
                };
            };
        };
        UpdateWikiPageRequest: {
            content: {
                "application/json": {
                    title?: string;
                    categorySlug?: string;
                    tags?: string[];
                    content?: string;
                    /** @enum {string} */
                    status?: "draft" | "published" | "archived";
                    changelog?: string;
                };
            };
        };
        CreateGuideRequest: {
            content: {
                "application/json": {
                    title: string;
                    slug?: string;
                    content: string;
                    tags?: string[];
                    /**
                     * @default draft
                     * @enum {string}
                     */
                    status?: "draft" | "published";
                    relatedCharacter?: string;
                };
            };
        };
        UpdateGuideRequest: {
            content: {
                "application/json": {
                    title?: string;
                    content?: string;
                    tags?: string[];
                    /** @enum {string} */
                    status?: "draft" | "published" | "archived";
                    relatedCharacter?: string;
                };
            };
        };
        RatingInput: {
            content: {
                "application/json": {
                    score: number;
                };
            };
        };
        CreateForumThreadRequest: {
            content: {
                "application/json": {
                    title: string;
                    content: string;
                    /** Format: uri */
                    coverImage?: string | null;
                };
            };
        };
        UpdateForumThreadRequest: {
            content: {
                "application/json": {
                    title?: string;
                    pinned?: boolean;
                    locked?: boolean;
                    /** Format: uri */
                    coverImage?: string | null;
                };
            };
        };
        CreateForumPostRequest: {
            content: {
                "application/json": {
                    content: string;
                };
            };
        };
        CreateCommentRequest: {
            content: {
                "application/json": {
                    content: string;
                };
            };
        };
        PresignUploadRequest: {
            content: {
                "application/json": {
                    filename: string;
                    contentType: string;
                    size?: number;
                };
            };
        };
    };
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 服务正常 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    getContentPage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: "home" | "world";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 页面内容 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentPageResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    putContentPage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: "home" | "world";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContentPageWrite"];
            };
        };
        responses: {
            /** @description 保存后的页面内容 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentPageResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    registerUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["RegisterRequest"];
        responses: {
            /** @description 注册成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["ValidationError"];
            409: components["responses"]["Conflict"];
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 当前用户 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    updateCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["UpdateCurrentUserRequest"];
        responses: {
            /** @description 更新后的用户 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 用户公开资料 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSummary"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    createSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["AuthSessionRequest"];
        responses: {
            /** @description 认证会话 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSession"];
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimited"];
        };
    };
    deleteSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已登出 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listWikiCategories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 分类列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WikiCategoryList"];
                };
            };
        };
    };
    listWikiPages: {
        parameters: {
            query?: {
                category?: string;
                tag?: string;
                q?: string;
                status?: "draft" | "published" | "archived";
                page?: components["parameters"]["Page"];
                perPage?: components["parameters"]["PerPage"];
                sort?: "updatedAt" | "createdAt" | "title";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 页面列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WikiPageList"];
                };
            };
        };
    };
    createWikiPage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["CreateWikiPageRequest"];
        responses: {
            /** @description 创建成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WikiPage"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    getWikiPage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["Slug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 页面详情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WikiPage"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteWikiPage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["Slug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已删除 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateWikiPage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["Slug"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["UpdateWikiPageRequest"];
        responses: {
            /** @description 更新后的页面 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WikiPage"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    listWikiPageRevisions: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                perPage?: components["parameters"]["PerPage"];
            };
            header?: never;
            path: {
                slug: components["parameters"]["Slug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 版本列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WikiPageRevisionList"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getWikiPageRevision: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["Slug"];
                revisionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 版本详情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WikiPageRevision"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listGuides: {
        parameters: {
            query?: {
                tag?: string;
                q?: string;
                status?: "draft" | "published" | "archived";
                sort?: "rating" | "updatedAt" | "createdAt";
                page?: components["parameters"]["Page"];
                perPage?: components["parameters"]["PerPage"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 攻略列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GuideList"];
                };
            };
        };
    };
    createGuide: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["CreateGuideRequest"];
        responses: {
            /** @description 创建成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Guide"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getGuide: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["Slug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 攻略详情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Guide"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteGuide: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["Slug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已删除 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateGuide: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["Slug"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["UpdateGuideRequest"];
        responses: {
            /** @description 更新后的攻略 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Guide"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getGuideRating: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["Slug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 评分汇总 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RatingSummary"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    rateGuide: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["Slug"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["RatingInput"];
        responses: {
            /** @description 评分结果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RatingSummary"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listForumBoards: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 板块列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForumBoardList"];
                };
            };
        };
    };
    listForumThreads: {
        parameters: {
            query?: {
                sort?: "lastPostAt" | "createdAt";
                page?: components["parameters"]["Page"];
                perPage?: components["parameters"]["PerPage"];
            };
            header?: never;
            path: {
                boardSlug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 主题列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForumThreadList"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    createForumThread: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                boardSlug: string;
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["CreateForumThreadRequest"];
        responses: {
            /** @description 发布成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForumThread"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getForumThread: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                threadId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 主题详情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForumThread"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteForumThread: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                threadId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已删除 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateForumThread: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                threadId: string;
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["UpdateForumThreadRequest"];
        responses: {
            /** @description 更新后的主题 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForumThread"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listForumPosts: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                perPage?: components["parameters"]["PerPage"];
            };
            header?: never;
            path: {
                threadId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 回复列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForumPostList"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    createForumPost: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                threadId: string;
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["CreateForumPostRequest"];
        responses: {
            /** @description 回复成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForumPost"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteForumPost: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                postId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已删除 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateForumPost: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                postId: string;
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["CreateForumPostRequest"];
        responses: {
            /** @description 更新后的回复 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForumPost"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    likeForumPost: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                postId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已点赞 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    unlikeForumPost: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                postId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已取消 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    bookmarkThread: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                threadId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已收藏 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    unbookmarkThread: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                threadId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已取消 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listWikiComments: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                perPage?: components["parameters"]["PerPage"];
            };
            header?: never;
            path: {
                slug: components["parameters"]["Slug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 评论列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentList"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    createWikiComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["Slug"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["CreateCommentRequest"];
        responses: {
            /** @description 评论成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comment"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listGuideComments: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                perPage?: components["parameters"]["PerPage"];
            };
            header?: never;
            path: {
                slug: components["parameters"]["Slug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 评论列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentList"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    createGuideComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["Slug"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["CreateCommentRequest"];
        responses: {
            /** @description 评论成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comment"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                commentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已删除 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                commentId: string;
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["CreateCommentRequest"];
        responses: {
            /** @description 更新后的评论 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comment"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    likeComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                commentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已点赞 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    unlikeComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                commentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已取消 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    search: {
        parameters: {
            query: {
                q: string;
                kind?: "all" | "wiki" | "guide" | "forum";
                page?: components["parameters"]["Page"];
                perPage?: components["parameters"]["PerPage"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 搜索结果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
        };
    };
    uploadFile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description 上传成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Upload"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            /** @description 文件过大 */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
        };
    };
    presignUpload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["PresignUploadRequest"];
        responses: {
            /** @description 预签名信息 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresignedUpload"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
        };
    };
}
